/*
Problem: find the difference
Link:
Difficulty: Easy 
Topic(s):
Pattern:

Description:
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.



Constraints:

Initial idea:
This seems like a simillar XORing idea where we use the ASCII values of the chars. 

Final approach:

Complexity:
Time:
Space:

Mistakes / difficulties:

Key lesson:

Review:
- Solved on:
- Revisit:
*/

#include <stdio.h>

char findTheDifference(char* s, char* t) {
	int s_sum = 0; 
	while (*s != '\0'){
		s_sum ^= *s; 
		s++; 
	}

	int t_sum = 0; 
	while (*t != '\0'){
		t_sum ^= *t; 
		t++; 
	}

	char res = t_sum ^ s_sum; 
	return res; 
}

int main(){
	char* s = "abcd"; 
	char* t = "abcde"; 
	char res = findTheDifference(s, t); 
	printf("%c\n", res);
	return 0; 
}